twig:
    file_name_pattern: '*.twig'
    paths:
        'templates/emails': "emails"
    # form_themes: ['bootstrap_5_layout.html.twig']
    form_themes: ['form-theme.html.twig']


when@test:
    twig:
        strict_variables: true
