controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

cgu:
    path: /cgu
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults: 
        template: cgu.html.twig

# redirecthomepage:
#     path: /homepage
#     controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
#     defaults:
#         route: 'blog_homepage'
#         permanent: true
#         keepQueryParams: true 



# index:
#   path: /
#   controller: App\Controller\DefaultController::index

# blog:
#   path: /blog
#   controller: App\Controller\DefaultController::blog